"""pymupdf4llm-based PDF -> Markdown converter.

This module intentionally imports `pymupdf4llm` lazily inside `convert()` so
that the base downloader can run without the optional markdown dependencies.
"""

from __future__ import annotations

import threading
from pathlib import Path

from .pdf_to_md import MarkdownConvertOptions


class Pymupdf4llmConverter:
    """Convert PDF to Markdown using pymupdf4llm."""

    _convert_lock = threading.Lock()

    def convert(
        self, pdf_path: str, md_path: str, *, options: MarkdownConvertOptions
    ) -> tuple[bool, str | None]:
        try:
            import pymupdf4llm  # type: ignore
        except Exception as e:  # pragma: no cover
            return False, f"pymupdf4llm is not installed: {e}"

        # pymupdf4llm has shown non-deterministic failures under concurrent usage.
        # Serialize conversion to prioritize robustness over throughput.
        with self._convert_lock:
            markdown_text, convert_error = self._convert_with_fallbacks(pymupdf4llm, pdf_path)
        if markdown_text is None:
            return False, convert_error or "Markdown conversion failed"

        try:
            output_path = Path(md_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            if output_path.exists() and not options.overwrite:
                return True, None
            output_path.write_text(markdown_text or "", encoding="utf-8")
        except Exception as e:
            return False, f"Failed to write markdown: {e}"

        return True, None

    def _convert_with_fallbacks(self, pymupdf4llm, pdf_path: str) -> tuple[str | None, str | None]:
        errors: list[str] = []

        # Primary attempt: default pymupdf4llm behavior.
        attempts = [
            ("default", {}),
            # Fallback 1: disable table extraction to avoid fragile table parsing paths.
            ("no_tables", {"table_strategy": ""}),
            # Fallback 2: also ignore graphics if page drawing objects are problematic.
            ("no_tables_no_graphics", {"table_strategy": "", "ignore_graphics": True}),
        ]

        for attempt_name, kwargs in attempts:
            try:
                markdown_text = pymupdf4llm.to_markdown(pdf_path, **kwargs)
                return markdown_text or "", None
            except Exception as e:
                errors.append(f"{attempt_name}: {e}")

        # Final fallback: extract plain text with PyMuPDF so --to-md remains usable.
        fallback_text, fallback_error = self._fallback_markdown_from_text(pdf_path)
        if fallback_text is not None:
            prefix = (
                "<!-- Fallback markdown generated by plain-text extraction "
                "because pymupdf4llm conversion failed. -->\n\n"
            )
            return prefix + fallback_text, None

        if fallback_error:
            errors.append(f"pymupdf_fallback: {fallback_error}")
        return None, " | ".join(errors) if errors else "Markdown conversion failed"

    def _fallback_markdown_from_text(self, pdf_path: str) -> tuple[str | None, str | None]:
        try:
            import pymupdf  # type: ignore
        except Exception as e:  # pragma: no cover
            return None, f"pymupdf is not installed: {e}"

        try:
            doc = pymupdf.open(pdf_path)
        except Exception as e:
            return None, str(e)

        try:
            sections: list[str] = []
            for page_index, page in enumerate(doc, start=1):
                text = page.get_text("text") or ""
                cleaned = text.strip()
                if not cleaned:
                    cleaned = "_(No extractable text on this page.)_"
                sections.append(f"## Page {page_index}\n\n{cleaned}")

            if not sections:
                sections.append("_(No pages found in document.)_")

            return "\n\n".join(sections).strip() + "\n", None
        except Exception as e:
            return None, str(e)
        finally:
            doc.close()
